branch-defaults:
  main:
    environment: DG-Backend-dev
    group_suffix: null
deploy:
  artifact: target/hellospringboot-0.0.1-SNAPSHOT.jar
global:
  application_name: DG-Backend
  branch: null
  default_ec2_keyname: dg-app-key
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
